project:
  type: website

website:
  title: "GeoNinjas"
  navbar:
    logo: images/logo.png
    left:
      - href: overview.qmd
        text: Overview
      - href: https://github.com/valtyl/IS415-GAA-Project/tree/master/others
        text: Research Paper
      - href: https://valtyl.shinyapps.io/IS415-GAA-Shiny/
        text: Shiny App
      - href: https://github.com/valtyl/IS415-GAA-Project/tree/master/others
        text: User Guide
      - href: poster.qmd
        text: Poster
    right:
      - href: about.qmd
        text: About
      - href: https://github.com/valtyl/IS415-GAA-Project
        text: Github
  
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

