project:
  type: website

website:
  title: "Tmappers"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: https://github.com/valtyl/IS415-GAA-Project
        text: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

