project:
  type: website

website:
  title: "GeoNinjas"
  navbar:
    logo: images/logo.png
    right:
      - href: about.qmd
        text: About
      - href: https://github.com/valtyl/IS415-GAA-Project
        text: Github
  
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

